schema_version = "1.0.0"
id = "asset_manager_by_zield"
version = "0.1.3-alpha"
name = "Asset Manager by Zield"
tagline = "Este addon permite tres formas de cargar assets: normalmente (carga el objeto 3D tal como se guardó), por material (aplica el material del asset a los objetos seleccionados) y por geometry nodes (aplica los geometry nodes del asset a los objetos seleccionados). Además, puede cargar solo la malla sin materiales ni modificadores. Otras funciones incluyen guardar assets y renombrarlos para un acceso fácil en una lista."
maintainer = "Zield555"
type = "add-on"
blender_version_min = "4.3.0"
license = ["SPDX:GPL-2.0-or-later"]
